### ISSUE TITLE
Physics-Informed Example

### ISSUE THREAD

**Issue by leonard-gleyzer** [google/sympy2jax#1]
Hello,

This library looks super interesting! I'd like to get a better understanding of how to potentially use it for my research with physics-informed models. Would you please be able to provide a small example of building such a model with sympy2jax side-by-side with the equivalent model using only Equinox?

Thank you!

**Comment by patrick-kidger** [comment]
This is really just a Sympy-JAX converter. Building a physics-informed model is up to you, really!

Nonetheless an existing example you could use as a starting point is [this example from the Diffrax documentation](https://docs.kidger.site/diffrax/examples/symbolic_regression/), which trains a neural ODE and then performs symbolic regression to obtain the vector field, from data, as a symbolic expression. (A bit like SINDy but a bit better.) This example hasn't been updated to use `sympy2jax` yet -- it uses an older less convenient tool -- but it should nonetheless be an example of the technique.

Also see [Section 6.1 of my thesis](https://arxiv.org/abs/2202.02435) for more discussion on the same technique.

Finally, do just look at the source code for `sympy2jax`. It's very short.

**Comment by leonard-gleyzer** [comment]
Thank you! That's very helpful.
